### ISSUE TITLE
Exception when using RFC2217 based connection (IDFGH-11250)

### ISSUE THREAD

**Issue by KlausPopp** [espressif/esp-idf-monitor#10]
Applies to `esp-idf-monitor` version 1.2.1.

I'm using a network tty, RFC2217 based to connect to the ESP serial line, so my `ESPPORT` is set to something like `rfc2217://192.168.11.12:3001?ign_set_control`.

When using idf.py monitor command, it throws an exception whenever it needs to close the serial port:
```
Exception in thread Thread-2 (_run_outer):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/esp/python_env/idf5.1_py3.10_env/lib/python3.10/site-packages/esp_idf_monitor/base/stoppable_thread.py", line 47, in _run_outer
    self.run()
  File "/opt/esp/python_env/idf5.1_py3.10_env/lib/python3.10/site-packages/esp_idf_monitor/base/serial_reader.py", line 100, in run
    self.close_serial()
  File "/opt/esp/python_env/idf5.1_py3.10_env/lib/python3.10/site-packages/esp_idf_monitor/base/serial_reader.py", line 105, in close_serial
    self._disable_closing_wait_or_discard_data()
  File "/opt/esp/python_env/idf5.1_py3.10_env/lib/python3.10/site-packages/esp_idf_monitor/base/serial_reader.py", line 119, in _disable_closing_wait_or_discard_data
    buf = fcntl.ioctl(self.serial.fd, termios.TIOCGSERIAL, buf)
AttributeError: 'Serial' object has no attribute 'fd'. Did you mean: 'cd'?
```
I guess it's because there is no `fd` for a rfc2217 connection.

Possible fix in `esp_idf_monitor/base/serial_reader.py`:
```
    def close_serial(self):
        if sys.platform == 'linux':
            # Avoid waiting for 30 seconds before closing the serial connection
            if hasattr(self.serial, 'fd'):
                self._disable_closing_wait_or_discard_data()
        self.serial.close()
```

**Comment by dobairoland** [comment]
Thanks @KlausPopp for the report. It should be fixed now.
